### ISSUE TITLE
Atom/RSS validation

### ISSUE THREAD

**Issue by peter279k** [selective-php/xml#3]
As title, should we add this validation to validate `Atom` formar XML?

## References
- https://validator.w3.org/feed/
- https://github.com/rubys/feedvalidator

**Comment by odan** [comment]
RSS 2.0 files can already be validated against this XSD-Schema: http://europa.eu/rapid/conf/RSS20.xsd
and Atom 1.0 can be validated against this XSD schema file: https://jvndb.jvn.jp/schema/atom.xsd.

For this reason a special validation for this formats is not really necessary (because it's already possible to validate against this schemas).

**Comment by peter279k** [comment]
Ok. That makes sense. Closed.
